### ISSUE TITLE
Please add 2-series Master Card validation.

### ISSUE THREAD

**Issue by chunghha** [Nightapes/ng2-validators#15]
Please add 2-series Master Card validation per this:
https://www.mastercard.us/en-us/issuers/get-support/2-series-bin-expansion.html

New 2-series BIN range will be 222100–272099.

**Comment by Nightapes** [comment]
I added it in version [1.7.0](https://github.com/Nightapes/ng2-validators/releases/tag/v1.7.0).
If you have problems, let me know

**Comment by chunghha** [comment]
Works fine. Thanks.
