### ISSUE TITLE
Angular-seed package

### ISSUE THREAD

**Issue by calhemp** [Nightapes/ng2-validators#26]
Hi, thanks for your efforts.

 I read that validator can be used with angular seed starter, but I don't have such experience (i'm new with angular) and tried 2 methods but all went with errors,
If anyone can help or reproduce for adding ng2-validators and works, can share their setup.

here are my errors:
https://github.com/mgechev/angular-seed my starter setup

editing in /tools/config/project.config.ts
1) first I tried editing project.config.ts and adding the bundle umd 
```
let additionalPackages: ExtendPackages[] = [
      {
        name: 'ng2-validators',
        path: 'node_modules/ng2-validators/bundles/ng2-validators.umd.js'
      },
    ];
    
    this.addPackagesBundles(additionalPackages);
```

> but when I run npm start it says in console
> "(SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/google-libphonenumber.js
> 	patchProperty/desc.set/wrapFn@http://localhost:5555/node_modules/zone.js/dist/zone.js?1489958749300:1242:26 [<root>]
> 	Zone.prototype.runTask@http://localhost:5555/node_modules/zone.js/dist/zone.js?1489958749300:166:28 [<root> => <root>]
> 	ZoneTask/this.invoke@http://localhost:5555/node_modules/zone.js/dist/zone.js?1489958749300:420:28 [<root>]
> 	
> 	Error loading http://localhost:5555/node_modules/google-libphonenumber.js as "google-libphonenumber" from http://localhost:5555/node_modules/ng2-validators/bundles/ng2-validators.umd.js" "Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues"  localhost:5555:67:7
> 

editing in /tools/config/seed.config.ts
2) if I comment (1) in project.config.ts and I add this lines in seed.config.ts

```
SYSTEM_CONFIG_DEV: any = {
    defaultJSExtensions: true,
    paths: {
      [this.BOOTSTRAP_MODULE]: `${this.APP_BASE}${this.BOOTSTRAP_MODULE}`,
      '@angular/common......
      
      'ng2-validators': 'node_modules/ng2-validators',
      .................
    },
    packages: {
      rxjs: {
        main: "./Rx.js",
        defaultExtension: 'js'
      },
      
      "ng2-validators": {
        main: './index',
        defaultExtension: 'js'
      },
      
    }
  };
```
it raises i console 

> "(SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/traceur.js
> 	patchProperty/desc.set/wrapFn@http://localhost:5555/node_modules/zone.js/dist/zone.js?1489959051078:1242:26 [<root>]
> 	Zone.prototype.runTask@http://localhost:5555/node_modules/zone.js/dist/zone.js?1489959051078:166:28 [<root> => <root>]
> 	ZoneTask/this.invoke@http://localhost:5555/node_modules/zone.js/dist/zone.js?1489959051078:420:28 [<root>]
> 	
> 	Error loading http://localhost:5555/node_modules/traceur.js
> 	Unable to load transpiler to transpile http://localhost:5555/node_modules/ng2-validators/index.js
> 	Error loading http://localhost:5555/node_modules/ng2-validators/index.js as "ng2-validators" from http://localhost:5555/app/app.module.js" "Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues"  localhost:5555:67:7

**Comment by calhemp** [comment]
finaly is working, sorry for my newbie

I added only this in project.config.ts and works now

```
 let additionalPackages: ExtendPackages[] = [
      {
        name: 'google-libphonenumber',
        path: 'node_modules/google-libphonenumber/dist/libphonenumber.js'
      },
      {
        name: 'ng2-validators',
        path: 'node_modules/ng2-validators/bundles/ng2-validators.umd.min.js'
      },
    ];
    
    this.addPackagesBundles(additionalPackages);
```

thanks I will try your validator now ;)

**Comment by Nightapes** [comment]
Hey, could that you could solve the problem. I added your solution to the README

Hope everything is working as aspected.

Can i close the issue?

**Comment by calhemp** [comment]
I Nightapes, yes, It works now well ;)
