### ISSUE TITLE
no whitespace or empty string

### ISSUE THREAD

**Issue by calhemp** [Nightapes/ng2-validators#27]
Hi, @Nightapes nice work.
I like noWhitespace validator for check if is no whitespace,
but, if in my input I write 'aaa bbb' says that is invalid because have a whitespace.

Hi, is posible to add a validator that can check if a form is empty or a string with only 1 whitespace character?

I think adding this could be good for check if input is not only a whitespace string.
like this, for example, http://stackoverflow.com/questions/39236992/how-to-validate-white-spaces-empty-spaces-angular-2

```
UniversalValidators.noEmptyString = function (control) {
    if (Util.isNotPresent(control))
        return undefined;
    let isWhitespace = (control.value || '').trim().length === 0;
    let isValid = !isWhitespace;
    return isValid ? undefined : { 'noEmptyString': true }
};
```

what do you think?
Pere

**Comment by Nightapes** [comment]
Hey, 

i can add this validator. 
But first i will upgrade to angular 4 :)

**Comment by Nightapes** [comment]
Should be there now in 2.1.0. Give it a try :)

**Comment by calhemp** [comment]
many thanks for the new validator feature @Nightapes.
tested and works ok.
we have another validator in the collection ;)

**Comment by Nightapes** [comment]
When you need a new one, open a new Issue or even better a Pull Request.
Good that everything works 👍
