### ISSUE TITLE
Add more valid region codes

### ISSUE THREAD

**Issue by AlanCrevon** [Nightapes/ng2-validators#31]
Hi.

Could you please add 'FR' as a valid region code in `ng2-validators/src/phone/phone-validators.ts` as it is officially supported by google-libphonenumber ?

Thanks for this wonderful lib. :)

Alan

**Comment by AlanCrevon** [comment]
mmm... There seems to be several other missing valid region codes.

In `google-libphonenumber/dist/libphonenumber.js`, there is a list of country codes in  `i18n.phonenumbers.metadata.countryCodeToRegionCodeMap`. 

Maybe this list could be parsed to build your `regionsCode`. I'm not good enough at JS yet to provide a usable PR. :/

**Comment by Nightapes** [comment]
Thank you for the PR!  
The region codes are available in version 2.1.1
