### ISSUE TITLE
Improve errors by including instantiation parameters

### ISSUE THREAD

**Issue by third774** [Nightapes/ng2-validators#35]
Currently, the errors that are put on the `FormControl.errors` are just a booleans, however it would be more useful for dynamically displaying error messages to provide an object (whose existence already indicates the error) and has properties containing the parameters used to construct the validator function.

For example, the `repeatCharacterRegexRule` error should have the number that was passed into it to create the rule.

**Comment by third774** [comment]
Furthermore, this would be in alignment with the errors created by Angular's default validators, such as the `maxLength` validator.

![image](https://cloud.githubusercontent.com/assets/8732191/24838816/0f498cb4-1d15-11e7-8bbc-aa68389b4cf9.png)

**Comment by Nightapes** [comment]
Hello,

thank you for the hint. I added more information to the error messages, when i have enough information.
See: https://github.com/Nightapes/ng2-validators/pull/36
