### ISSUE TITLE
ng-invalid class is not getting remove from the input field even if the input field is valid

### ISSUE THREAD

**Issue by Nikhil-Pahwa** [Nightapes/ng2-validators#9]
I am using the min , max attribute of the ng2-validators library. The ng-invalid class is not getting removed  from the input field even the input is valid. 
This makes my whole form invalid. Can you suggest me something if how can i see check the form validity?
Thanks in advance

**Comment by Nightapes** [comment]
Hello, can you send me a small code example?

**Comment by Nikhil-Pahwa** [comment]
Hi, Please look the code below: 
`<form class="form-horizontal span12 ng-pristine ng-invalid ng-touched" name="attribution">
		<div class="row-fluid form-inline">
			<span class="optionHeading span2">Demo 1:</span>
			<input class="span2 ng-untouched ng-pristine ng-valid" name="url" type="text" ng-reflect-name="url" ng-reflect-placeholder="URL" placeholder="URL" ng-reflect-model="http://pdns.cybertrap.com:5000/lookup">       
		</div>
		<div class="row-fluid form-inline">
			<span class="optionHeading span2">Demo 2:</span>
			<input class="span2 ng-untouched ng-pristine ng-valid" name="key" type="text" ng-reflect-name="key" ng-reflect-placeholder="Key" placeholder="Key" ng-reflect-model="euqu3Yagh5thienithizeiquaecareuf">      
		</div>
		<div class="row-fluid form-inline">
			<span class="optionHeading span2">Demo 3:</span>
			<input class="span2 ng-pristine ng-invalid ng-touched" isinrange="" minutes._status="" name="minutes" required="" type="number" ng-reflect-min="1" ng-reflect-max="32000" ng-reflect-name="minutes" ng-reflect-placeholder="In minutes" placeholder="In minutes" ng-reflect-model="12320">
		</div>
		<div class="row-fluid form-inline">
			<span class="optionHeading span2">Demo 4:</span>
			<input class="span2 ng-untouched ng-pristine ng-invalid" depth._status="" isinrange="" name="depth" required="" type="number" ng-reflect-min="1" ng-reflect-max="10" ng-reflect-name="depth" ng-reflect-placeholder="How deep we should go?" placeholder="How deep we should go?" ng-reflect-model="6">
		</div>
		<div class="row-fluid form-inline">
			<span class="optionHeading span2">Demo 5:</span>
			<input class="span2 ng-untouched ng-pristine ng-invalid" isinrange="" name="threshold" required="" threshold._status="" type="number" ng-reflect-min="1" ng-reflect-max="32000" ng-reflect-name="threshold" ng-reflect-placeholder="Threshold" placeholder="Threshold" ng-reflect-model="62">       
		</div>           
		<div class="modification-btn">
			<div>
				<button class="btn btn-default btn-space reset-btn" id="resetNameBtn" type="button">Reset</button>
				<button class="btn btn-default btn-space cancel-btn" id="cancelNameBtn" type="button">Cancel</button>
				<button class="btn btn-primary btn-space save-btn" id="saveNameBtn" type="submit">Save</button>        
			</div>
		</div>
</form>`

In the above form we are using ng2 validators range check on number fields. Despite of number fields value being valid the class ng-invalid is not getting removed on these fields. Due to which the form remains invalid. We can not use the validity of the form for blocking the control on UI.

**Comment by Nightapes** [comment]
Are you using Angular 1 or Angular 2? 
This lib is only for Angular 2

**Comment by Nikhil-Pahwa** [comment]
I am using final Angular2 release.

**Comment by Nikhil-Pahwa** [comment]
The earlier code i have shared was copied from dev tools of google chrome. Therefore maybe more classes are added. Here is a new sample code 
`<form name="attribution" class="form-horizontal span12">
    <div class="row-fluid form-inline">
        <span class="optionHeading span2">attribution</span>
        <input name="minutes" class="span2" type="number" [(ngModel)]='model.attribution.maxEntryAge'
            isInRange [min]="1" [max]="32000" #minutes="ngModel" required minutes._status [class.error]="minutes.errors?.rangeValueToBig || minutes.errors?.rangeValueToSmall"
        />
        <span *ngIf="minutes.errors?.rangeValueToSmall" class="error-message msg-bubble">Max entry age must be between 1 and 32000</span>       
    </div>    
</form>`

As you can see in the code snippet that the range of the input field should be between 1 to 32000. When i give a number like 500 in the input field the ng-invalid class is not removed. Please look below the output code.

`<input class="span2 ng-invalid ng-touched ng-dirty" isinrange="" minutes._status="" name="minutes" required="" type="number" ng-reflect-min="1" ng-reflect-max="32000" ng-reflect-name="minutes" ng-reflect-placeholder="In minutes" placeholder="In minutes" ng-reflect-model="500">`

To my understanding that the 500 is a valid number therefore the ng-invalid class should be removed from this input field. 

Please guide me if i am missing anything. Thanks in advance

**Comment by Nightapes** [comment]
Hey @Nikhil-Pahwa ,
 i found the problem. Can you update to Version 1.5.2
You have to rename `[min]` to `[minValue]` and `[max]` to `[maxValue]`

Working example: 
```
<form name="attribution">
    <input name="minutes" type="number" [(ngModel)]='model.range' isInRange [minValue]="1" [maxValue]="32000" require #formControl="ngModel">
</form>
<span *ngIf="formControl.errors?.numberRequired">Needs to be a number</span>
<span *ngIf="formControl.errors?.rangeValueToSmall">Number to small</span>
<span *ngIf="formControl.errors?.rangeValueToBig">Number to big</span>
```

Thank you for founding the bug and sry that it take that long. 
Hope it solves your problem!

**Comment by Nikhil-Pahwa** [comment]
Work like a charm now +1:
:)
